# .github/workflows/ci.yml
name: CI/CD Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Checkout the code

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - run: npm install  # Install dependencies

    - run: npm test  # Run tests

    - run: npm run build  # Build the project

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      run: |
        npm install -g gh-pages
        npm run deploy
