name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Update status to pending
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          https://api.github.com/repos/aryaman1411/demo_cprime_github/statuses/${{ github.sha }} \
          -d '{"state":"pending","description":"Build is in progress","context":"continuous-integration/jenkins"}'

    - name: Run tests
      run: npm test

    - name: Update status to success
      if: success()
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          https://api.github.com/repos/aryaman1411/demo_cprime_github/statuses/${{ github.sha }} \
          -d '{"state":"success","description":"Build succeeded","context":"continuous-integration/jenkins"}'

    - name: Update status to failure
      if: failure()
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          https://api.github.com/repos/aryaman1411/demo_cprime_github/statuses/${{ github.sha }} \
          -d '{"state":"failure","description":"Build failed","context":"continuous-integration/jenkins"}'
